### ISSUE TITLE
Push versions to RubyGems?

### ISSUE THREAD

**Issue by tomchentw** [Roonin-mx/livescript-source#5]
We can only find `1.0.1` on http://rubygems.org/gems/livescript-source
:(

@Roonin-mx ?

**Comment by bianjp** [comment]
It hasn't been updated for over two years.

If no one is maintaining this gem (and [livescript](https://rubygems.org/gems/livescript), [livescript-rails](https://rubygems.org/gems/livescript-rails)), would you mind transfer the ownship to me or add me as a collaborator?

I like LiveScript very much and my company is using Rails as primary backend framework, so I'll be very pleased to maintain these gems.
