### ISSUE TITLE
I'd like to maintain this gem

### ISSUE THREAD

**Issue by bianjp** [Roonin-mx/livescript-source#6]
It hasn't been updated for over two years.

If no one is maintaining this gem (and [livescript](https://rubygems.org/gems/livescript), [livescript-rails](https://rubygems.org/gems/livescript-rails)), would you mind transfer the ownship to me or add me as a collaborator?

I like LiveScript very much and my company is using Rails as primary backend framework, so I'll be very pleased to maintain these gems.

**Comment by bianjp** [comment]
@hesenrre  @nizi 
Anyone is responsible for these gems?

**Comment by hesenrre** [comment]
Hi for some reason we have not been maintaining this gem (we have been working on other projects), but sure we are welcoming any contribution you can make. I'm adding you as a collaborator to the project

**Comment by bianjp** [comment]
Thanks!
Could you also add me as a collaborator to repos [livescript-ruby](https://github.com/Roonin-mx/livescript-ruby) and [livescript-rails](https://github.com/Roonin-mx/livescript-rails)? And also these gems on rubygems.org ([my profile](https://rubygems.org/profiles/bianjp)).

**Comment by hesenrre** [comment]
Done my friend

**Comment by bianjp** [comment]
Seems I don't have write access to livescript-ruby and livescript-rails yet.
![screenshot from 2016-04-19 10-28-41](https://cloud.githubusercontent.com/assets/4749277/14626127/7c385df8-061b-11e6-95f6-cd704e369394.png)

**Comment by hesenrre** [comment]
try again

**Comment by bianjp** [comment]
All is well. Thanks!

**Comment by bianjp** [comment]
Oh, you haven't add me as a collaborator to [livescript-source gem](https://rubygems.org/gems/livescript-source) yet.

**Comment by hesenrre** [comment]
check again

**Comment by bianjp** [comment]
Now everything seems ok. Thanks.

**Comment by bianjp** [comment]
@hesenrre 
Sorry to bother again.

Could you please enable the `issues` feature of repos [Roonin-mx/livescript-rails](https://github.com/Roonin-mx/livescript-rails) and [Roonin-mx/livescript-ruby](https://github.com/Roonin-mx/livescript-ruby)?

And please update the description of `Roonin-mx/livescript-rails` to "LiveScript asset pipeline for Rails >= 4.1". The new version I just released doesn't work with Rails 3.1 ~ 4.0 any more.

I hope that you can give me admin rights of these 3 repos. I have the plan to integrate [Travis-CI](https://travis-ci.org) to automatically test for different environments (ruby version, rails version) , and it can't be done without admin rights.

**Comment by hesenrre** [comment]
@bianjp don't worry I grant you access and made the changes you asked for, happy hacking
